### ISSUE TITLE
Why not use either the zf2 or doctrine cache libraries?

### ISSUE THREAD

**Issue by superdweebie** [zoopcommerce/juggernaut#1]

**Comment by joshystuart** [comment]
Ugh :( I didn't even think of those. I searched google for "php caching library" and nothing of real use came up!

I'll benchmark against mine to see if there's any difference.

I haven't looked at their code yet but I spent a bit of time getting mine to queue caching requests so that on a first hit or re-cache, you dont get a flood of requests. They just queue nicely and wait till the cache is ready. It also serves old cache (if it exists) for queued requests while a new version is being prepared.

The problem with our current file caching is that if a page has old cache, then we get a tonne of concurrent connections, it just kills the server and we don't have time to scale up to meet demand. So I'm going to cache the full page on the front end every 5 mins and make use of the flood protection to ensure the aforementioned problem doesn't occur.

**Comment by joshystuart** [comment]
At the moment with no optimization here are the stats from Apache Bench (results are requests per second, higher is better):

###### 10 concurrent, 100 connections (ab -k -c 10 -n 100)

```
Zoop: 24.29 23.97 23.91
Zend: 10.31 10.23 11.69
```

###### 20 concurrent, 100 connections (ab -k -c 20 -n 100)

```
Zoop: 23.55 21.56 23.24
Zend: 10.29 8.21 9.49
```

###### 100 concurrent, 200 connections (ab -k -c 100 -n 200)

```
Zoop: 45.41 35.78 39.94
Zend: 12.28 12.96 13.28
```

So at worst mine is ~100% better. I'm not sure if that is to do with the number of classes/files that Zend has to bootstrap, but I assume that zendoptimizer/apc would take care of that since I'm not flushing the opcode cache.

I reckon this difference may be due to the flood protection and queuing though. I can't see anything in their code that handles it but it may be there.
